In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
def diff(f, x, delta = 1e-6):
  return (f(x+delta) - f(x-delta))/(2*delta)

# Метод дихотомії


In [ ]:
e = 0.0001
f = lambda x: 2 ** x + np.e ** (-x) - 5 * x + 1
f_one = lambda x: 2 ** x * np.log(2) - math.e ** (-x) - 5
f_two = lambda x: 2 ** x * np.log(2) ** 2 + math.e ** (-x)



phi = lambda x: x - 0.04 * (x ** 3 - 2 * x + 4)

a_start = 0
b_start = 1

In [ ]:
# f = lambda x: 0.3 * math.cos(x)**2 - math.log(x) + 2
# f_one = lambda x: -0.6 * np.cos(x) * np.sin(x) - 1 / x

# a_start = 8.5
# b_start = 8.9

In [ ]:
data_for_print = {'α':[], 'f(α)':[], 'β':[], 'f(β)':[],'x*':[], 'f(x*)':[], '|β-α|':[], '|β-α|<ε':[]}

a = a_start
b = b_start

is_end = False
while not is_end:
  data_for_print['α'].append(round(a, 4))
  data_for_print['f(α)'].append(round(f(a), 4))
  data_for_print['β'].append(round(b, 4))
  data_for_print['f(β)'].append(round(f(b), 4))
  x = (a+b)/2
  data_for_print['x*'].append(round(x, 4))
  data_for_print['f(x*)'].append(round(f(x), 4))
  err = abs(b-a)
  data_for_print['|β-α|'].append(round(err, 4))
  is_end = err < e
  data_for_print['|β-α|<ε'].append(is_end)
  if f(a)*f(x) >= 0:
    a = x
  if f(b)*f(x) >= 0:
    b = x


In [ ]:
pd.DataFrame(data_for_print)

α    f(α)       β    f(β)      x*   f(x*)   |β-α|  |β-α|<ε
0   0.0000  3.0000  1.0000 -1.6321  0.5000  0.5207  1.0000    False
1   0.5000  0.5207  1.0000 -1.6321  0.7500 -0.5958  0.5000    False
2   0.5000  0.5207  0.7500 -0.5958  0.6250 -0.0475  0.2500    False
3   0.5000  0.5207  0.6250 -0.0475  0.5625  0.2341  0.1250    False
4   0.5625  0.2341  0.6250 -0.0475  0.5938  0.0927  0.0625    False
5   0.5938  0.0927  0.6250 -0.0475  0.6094  0.0224  0.0312    False
6   0.6094  0.0224  0.6250 -0.0475  0.6172 -0.0126  0.0156    False
7   0.6094  0.0224  0.6172 -0.0126  0.6133  0.0049  0.0078    False
8   0.6133  0.0049  0.6172 -0.0126  0.6152 -0.0039  0.0039    False
9   0.6133  0.0049  0.6152 -0.0039  0.6143  0.0005  0.0020    False
10  0.6143  0.0005  0.6152 -0.0039  0.6147 -0.0017  0.0010    False
11  0.6143  0.0005  0.6147 -0.0017  0.6145 -0.0006  0.0005    False
12  0.6143  0.0005  0.6145 -0.0006  0.6144 -0.0000  0.0002    False
13  0.6143  0.0005  0.6144 -0.0000  0.6143  0.0003  0.0001    False
14  0.6143  0.0003  0.6144 -0.0000  0.6143  0.0001  0.0001     True

# Метод хорд

In [ ]:
data_for_print = {'α':[], 'f(α)':[], 'β':[], 'f(β)':[],'x_k':[], 'f(x_k)':[], '|x_k - x_k-1|':[], '|x_k - x_k-1|<E':[]}
delta = math.inf

a = a_start
b = b_start

def delta_adding(xk_old, immoveble):
  if xk_old == immoveble:
    xk = xk_old
  else:
    xk = xk_old - f(xk_old)*(xk_old-immoveble)/(f(xk_old)-f(immoveble))

  data_for_print['x_k'].append(round(xk, 4))
  data_for_print['f(x_k)'].append(round(f(xk), 4))
  delta = abs(xk - xk_old)
  data_for_print['|x_k - x_k-1|'].append(round(delta, 4))
  data_for_print['|x_k - x_k-1|<E'].append(delta < e)
  return xk, delta



while delta > e:
  data_for_print['α'].append(round(a, 4))
  data_for_print['f(α)'].append(round(f(a), 4))
  data_for_print['β'].append(round(b, 4))
  data_for_print['f(β)'].append(round(f(b), 4))

  if f(a)*f_two(a) >= 0:
    xk_old = b
    immoveble = a

    xk, delta = delta_adding(xk_old, immoveble)

    b = xk

  elif f(b)*f_two(b) >= 0:
    xk_old = a
    immoveble = b

    xk, delta = delta_adding(xk_old, immoveble)

    a = xk
  else:
    print('error!')



In [ ]:
pd.DataFrame(data_for_print)

α  f(α)       β    f(β)     x_k  f(x_k)  |x_k - x_k-1|  |x_k - x_k-1|<E
0  0   3.0  1.0000 -1.6321  0.6477 -0.1484         0.3523            False
1  0   3.0  0.6477 -0.1484  0.6171 -0.0123         0.0305            False
2  0   3.0  0.6171 -0.0123  0.6146 -0.0010         0.0025            False
3  0   3.0  0.6146 -0.0010  0.6144 -0.0001         0.0002            False
4  0   3.0  0.6144 -0.0001  0.6144 -0.0000         0.0000             True

# Метод дотичних

In [ ]:
data_for_print = {'x0':[], 'f(x0)':[], "f'(x0)":[], 'x_k':[], "|f(x_k-1) / f'(x_k-1)|<E":[]}

a = a_start
b = b_start

is_end = False

x0 = [(i, f(i)*f_two(i)) for i in [a,b]]
if x0[0][1] < 0:
  x0 = x0[1][0]
elif x0[1][1] < 0:
  x0 = x0[0][0]
elif x0[1][1] > x0[0][1]:
  x0 = x0[0][0]
else:
  x0 = x0[1][0]
while not is_end:
  data_for_print['x0'].append(round(x0, 4))
  data_for_print['f(x0)'].append(round(f(x0), 4))
  data_for_print["f'(x0)"].append(round(f_one(x0), 4))
  xk = x0 - f(x0)/f_one(x0)
  data_for_print['x_k'].append(round(xk, 4))
  is_end = abs(f(x0)/f_one(x0))<e
  data_for_print["|f(x_k-1) / f'(x_k-1)|<E"].append(is_end)
  x0 = xk


In [ ]:
pd.DataFrame(data_for_print)

x0   f(x0)  f'(x0)     x_k  |f(x_k-1) / f'(x_k-1)|<E
0  0.0000  3.0000 -5.3069  0.5653                     False
1  0.5653  0.2214 -4.5425  0.6140                     False
2  0.6140  0.0015 -4.4803  0.6144                     False
3  0.6144  0.0000 -4.4798  0.6144                      True

# Метод простих ітерацій

In [ ]:
phi = lambda x: x + 0.2 * (f(x))
data_for_print = {'k':[], 'xk':[], "φ(xk)":[], "|x_k+1 - x_k|":[], "|x_k+1 - x_k|<ε":[]}

a = a_start
b = b_start

is_end = False

x0 = a
k = 0
while not is_end:
  data_for_print['k'].append(k)
  k+=1
  data_for_print['xk'].append(x0)
  if(abs(diff(phi, x0))>=1):
    print(f"Похідна від ф у точці {x0} приймає значення {diff(phi, x0)}")
    break
  xk = phi(x0)
  data_for_print['φ(xk)'].append(xk)
  is_end = abs(x0-xk)<e
  data_for_print["|x_k+1 - x_k|"].append(abs(x0-xk))
  data_for_print["|x_k+1 - x_k|<ε"].append(is_end)
  x0 = xk
len(data_for_print['φ(xk)'])

5

In [ ]:
pd.DataFrame(data_for_print)

k        xk     φ(xk)  |x_k+1 - x_k|  |x_k+1 - x_k|<ε
0    0  0.000000  0.300000       0.300000            False
1    1  0.300000  0.447196       0.147196            False
2    2  0.447196  0.523879       0.076683            False
3    3  0.523879  0.564943       0.041064            False
4    4  0.564943  0.587244       0.022301            False
5    5  0.587244  0.599445       0.012201            False
6    6  0.599445  0.606147       0.006703            False
7    7  0.606147  0.609837       0.003690            False
8    8  0.609837  0.611871       0.002034            False
9    9  0.611871  0.612993       0.001122            False
10  10  0.612993  0.613612       0.000619            False
11  11  0.613612  0.613954       0.000342            False
12  12  0.613954  0.614142       0.000189            False
13  13  0.614142  0.614246       0.000104            False
14  14  0.614246  0.614304       0.000057             True

# Схема Холецького

In [ ]:
def true_print(data):
  display(pd.DataFrame(data))

def hypatia_paste(some_data):
  for i in some_data:
    print('{', end='')
    print('}&{'.join(list(map(str, i))).replace('.',','), end='')
    print('}', end='')
    print('\\\\')

def display_with_hypatia(data):
  true_print(data)
  hypatia_paste(data)

def prepare_data(data):
  data = data.replace("\\","").replace(',','.').replace("{","").replace("}","").split('\n')
  data = np.array([np.array(list(map(float, i.split('&')))) for i in data])
  return data

In [ ]:
def Choletskogo(data):
    sh = data.shape[0]
    L, U = np.zeros((sh, sh)), np.zeros((sh, sh))

    for i in range(sh):
        L[i, i] = U[i, i] = 1

    for i in range(sh):
        L[i:, i] = data[i:, i] - np.matmul(L[i:, :i], U[:i, i])
        U[i, i:] = 1 / L[i, i] * (data[i, i:] - np.matmul(L[i, :i], U[:i, i:]))

    L = np.round(L, 3)
    U = np.round(U, 3)
    determinant = np.prod([j[i] for i,j in enumerate(L)])

    return L, U, determinant

In [ ]:
data = '''{1.66}&{0.52}&{0.82}&{0.38}\\
{0.78}&{1.69}&{1.56}&{0.49}\\
{0.76}&{1.44}&{1.61}&{0.46}\\
{0.44}&{0.73}&{0.34}&{1.40}\\'''
data = prepare_data(data)
(L, U, determinant) = Choletskogo(data)


print("L:")
display_with_hypatia(L)
print("U:")
display_with_hypatia(U)

print("Результати:")
print("Наш:", round(determinant, 3))
print("Програмно:", round(np.linalg.det(data), 3))

L:


0      1      2      3
0  1.66  0.000  0.000  0.000
1  0.78  1.446  0.000  0.000
2  0.76  1.202  0.258  0.000
3  0.44  0.592 -0.359  1.209

{1,66}&{0,0}&{0,0}&{0,0}\\
{0,78}&{1,446}&{0,0}&{0,0}\\
{0,76}&{1,202}&{0,258}&{0,0}\\
{0,44}&{0,592}&{-0,359}&{1,209}\\
U:


0      1      2      3
0  1.0  0.313  0.494  0.229
1  0.0  1.000  0.813  0.215
2  0.0  0.000  1.000  0.105
3  0.0  0.000  0.000  1.000

{1,0}&{0,313}&{0,494}&{0,229}\\
{0,0}&{1,0}&{0,813}&{0,215}\\
{0,0}&{0,0}&{1,0}&{0,105}\\
{0,0}&{0,0}&{0,0}&{1,0}\\
Результати:
Наш: 0.749
Програмно: 0.749


# Метод прогонки

In [ ]:
coefs = np.array([
    np.array([ 5,  -1,  0,   0]),
    np.array([ 2,  4.6, -1,  0]),
    np.array([ 0,  2,   3.6, -0.8]),
    np.array([ 0,  0,   3,   4.4]),
]
)
di = np.array([
    2,
    3.3,
    2.6,
    7.2
])

In [ ]:
bi = [-i[j] for j,i in enumerate(coefs)]
bi = np.array(bi)
bi

array([-5. , -4.6, -3.6, -4.4])

In [ ]:
ai = [0]
ai.extend([i[j] for j,i in enumerate(coefs[1:])])
ai = np.array(ai)
ai

array([0., 2., 2., 3.])

In [ ]:
ci = [i[j+1] for j,i in enumerate(coefs[:-1])]
ci.extend([0])
ci = np.array(ci)
ci

array([-1. , -1. , -0.8,  0. ])

In [ ]:
alpha = [ci[0]/bi[0]]
gama = [-di[0]/bi[0]]

for i,b,c,a,d in zip(range(0,len(bi)-2), bi[1:-1],ci[1:-1],ai[1:-1], di[1:-1]):
  alpha.append(c/(b-a*alpha[i]))
  gama.append((a*gama[i] - d)/(b-a*alpha[i]))
print("α =",np.round(alpha,3))
print("γ =",np.round(gama,3))

α = [0.2 0.2 0.2]
γ = [0.4 0.5 0.4]


In [ ]:
n = len(di)
xi = [0 for _ in range(n)]
xi[-1] = (ai[-1]*gama[-1]-di[-1])/(bi[-1]-ai[-1]*alpha[-1])

In [ ]:
for i in range(n-2, -1, -1):
  xi[i] = alpha[i]*xi[i+1]+gama[i]
for j,i in enumerate(np.round(xi,3)):
  print(f"x_{j+1} = {i}")

x_1 = 0.526
x_2 = 0.628
x_3 = 0.64
x_4 = 1.2
